### ISSUE TITLE
Free Gift duplicate when Create Order at Backend(Admin Page)

### ISSUE THREAD

**Issue by Osara12** [code4business/freeproduct2#26] opened 2020-05-07 09:24 UTC
### Preconditions

- Magento version: 2.3.4
- Module version: lastest

### Settings / Sale Rules
 1.Subtotal >= 2500 get free 1 item(1sku)

### Steps to reproduce
1.  Create order at Admin backend
2.  After added some product and Cart subtotal > 2500, the gift will be added to Cart
3.  if I add more products, The gift will duplicate. 
4. after placed order, The gift that duplicated from step 3 will show x2 at Order page.

### Expected result
1.

### Actual result
1.

**Comment by domeglic** [comment] 2022-08-10 10:21
duplicate of #35

**Closed as completed by domeglic** 2022-08-10 10:21 UTC
Labels: duplicate
